/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/history/2022-nian-zong-jie': RouteRecordInfo<'/posts/history/2022-nian-zong-jie', '/posts/history/2022-nian-zong-jie', Record<never, never>, Record<never, never>>,
    '/posts/history/20220714-hui-tou-kan-wang-qian-zou': RouteRecordInfo<'/posts/history/20220714-hui-tou-kan-wang-qian-zou', '/posts/history/20220714-hui-tou-kan-wang-qian-zou', Record<never, never>, Record<never, never>>,
    '/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi': RouteRecordInfo<'/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi', '/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi', Record<never, never>, Record<never, never>>,
    '/posts/history/cc1-lian-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/cc1-lian-xue-xi-bi-ji', '/posts/history/cc1-lian-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji': RouteRecordInfo<'/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji', '/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian': RouteRecordInfo<'/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian', '/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian', Record<never, never>, Record<never, never>>,
    '/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian': RouteRecordInfo<'/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian', '/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian', Record<never, never>, Record<never, never>>,
    '/posts/hola': RouteRecordInfo<'/posts/hola', '/posts/hola', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
