/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/history/2022-nian-zong-jie': RouteRecordInfo<'/posts/history/2022-nian-zong-jie', '/posts/history/2022-nian-zong-jie', Record<never, never>, Record<never, never>>,
    '/posts/history/20220714-hui-tou-kan-wang-qian-zou': RouteRecordInfo<'/posts/history/20220714-hui-tou-kan-wang-qian-zou', '/posts/history/20220714-hui-tou-kan-wang-qian-zou', Record<never, never>, Record<never, never>>,
    '/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi': RouteRecordInfo<'/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi', '/posts/history/aws-chang-jian-an-quan-wen-ti-zong-jie-yi', Record<never, never>, Record<never, never>>,
    '/posts/history/cc1-lian-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/cc1-lian-xue-xi-bi-ji', '/posts/history/cc1-lian-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji': RouteRecordInfo<'/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji', '/posts/history/code-audit-challengesphp-shua-ti-ji-lu-li-shi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/cve-2018-0114': RouteRecordInfo<'/posts/history/cve-2018-0114', '/posts/history/cve-2018-0114', Record<never, never>, Record<never, never>>,
    '/posts/history/cve-2023-50164-lou-dong-fen-xi-yu-xue-xi': RouteRecordInfo<'/posts/history/cve-2023-50164-lou-dong-fen-xi-yu-xue-xi', '/posts/history/cve-2023-50164-lou-dong-fen-xi-yu-xue-xi', Record<never, never>, Record<never, never>>,
    '/posts/history/geng-xin-liao-blog-nei-de-htb-de-wen-zhang-she-zhi-jia-mi': RouteRecordInfo<'/posts/history/geng-xin-liao-blog-nei-de-htb-de-wen-zhang-she-zhi-jia-mi', '/posts/history/geng-xin-liao-blog-nei-de-htb-de-wen-zhang-she-zhi-jia-mi', Record<never, never>, Record<never, never>>,
    '/posts/history/gogs-rce-li-shi-lou-dong-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/gogs-rce-li-shi-lou-dong-xue-xi-bi-ji', '/posts/history/gogs-rce-li-shi-lou-dong-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/google-dorking-learn': RouteRecordInfo<'/posts/history/google-dorking-learn', '/posts/history/google-dorking-learn', Record<never, never>, Record<never, never>>,
    '/posts/history/gruyereorbi-ji-yi-ge-web-ping-tai-de-lou-dong-xue-xi-bi-ji-': RouteRecordInfo<'/posts/history/gruyereorbi-ji-yi-ge-web-ping-tai-de-lou-dong-xue-xi-bi-ji-', '/posts/history/gruyereorbi-ji-yi-ge-web-ping-tai-de-lou-dong-xue-xi-bi-ji-', Record<never, never>, Record<never, never>>,
    '/posts/history/guan-yu-mu-lu-bian-li-lou-dong-zhong-fei-biao-zhun-bian-ma-c02f-he-c0af-jun-neng-dai-biao-qie-jun-zai-lou-dong-zhong-sheng-xiao-de-yuan-li-tan-suo': RouteRecordInfo<'/posts/history/guan-yu-mu-lu-bian-li-lou-dong-zhong-fei-biao-zhun-bian-ma-c02f-he-c0af-jun-neng-dai-biao-qie-jun-zai-lou-dong-zhong-sheng-xiao-de-yuan-li-tan-suo', '/posts/history/guan-yu-mu-lu-bian-li-lou-dong-zhong-fei-biao-zhun-bian-ma-c02f-he-c0af-jun-neng-dai-biao-qie-jun-zai-lou-dong-zhong-sheng-xiao-de-yuan-li-tan-suo', Record<never, never>, Record<never, never>>,
    '/posts/history/guan-yu-opener-de-xue-xi-ji-li-yong': RouteRecordInfo<'/posts/history/guan-yu-opener-de-xue-xi-ji-li-yong', '/posts/history/guan-yu-opener-de-xue-xi-ji-li-yong', Record<never, never>, Record<never, never>>,
    '/posts/history/htb-petpet-rcbee': RouteRecordInfo<'/posts/history/htb-petpet-rcbee', '/posts/history/htb-petpet-rcbee', Record<never, never>, Record<never, never>>,
    '/posts/history/htb-templated-or-writeup': RouteRecordInfo<'/posts/history/htb-templated-or-writeup', '/posts/history/htb-templated-or-writeup', Record<never, never>, Record<never, never>>,
    '/posts/history/htb-weather-App': RouteRecordInfo<'/posts/history/htb-weather-App', '/posts/history/htb-weather-App', Record<never, never>, Record<never, never>>,
    '/posts/history/htbbackend-api': RouteRecordInfo<'/posts/history/htbbackend-api', '/posts/history/htbbackend-api', Record<never, never>, Record<never, never>>,
    '/posts/history/htbencoding': RouteRecordInfo<'/posts/history/htbencoding', '/posts/history/htbencoding', Record<never, never>, Record<never, never>>,
    '/posts/history/htbforgot': RouteRecordInfo<'/posts/history/htbforgot', '/posts/history/htbforgot', Record<never, never>, Record<never, never>>,
    '/posts/history/htbmentor': RouteRecordInfo<'/posts/history/htbmentor', '/posts/history/htbmentor', Record<never, never>, Record<never, never>>,
    '/posts/history/htbphonebook-or-writeup': RouteRecordInfo<'/posts/history/htbphonebook-or-writeup', '/posts/history/htbphonebook-or-writeup', Record<never, never>, Record<never, never>>,
    '/posts/history/htbvessel': RouteRecordInfo<'/posts/history/htbvessel', '/posts/history/htbvessel', Record<never, never>, Record<never, never>>,
    '/posts/history/java-rmiremote-method-invocation': RouteRecordInfo<'/posts/history/java-rmiremote-method-invocation', '/posts/history/java-rmiremote-method-invocation', Record<never, never>, Record<never, never>>,
    '/posts/history/java-xue-xi-bi-ji-servlet': RouteRecordInfo<'/posts/history/java-xue-xi-bi-ji-servlet', '/posts/history/java-xue-xi-bi-ji-servlet', Record<never, never>, Record<never, never>>,
    '/posts/history/javascript-prototype-pollution-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/javascript-prototype-pollution-xue-xi-bi-ji', '/posts/history/javascript-prototype-pollution-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/ji-zhu-fen-xiang-hui-wo-dui-yu-flask-jin-qi-li-jie-de-yi-ge-gao-zi': RouteRecordInfo<'/posts/history/ji-zhu-fen-xiang-hui-wo-dui-yu-flask-jin-qi-li-jie-de-yi-ge-gao-zi', '/posts/history/ji-zhu-fen-xiang-hui-wo-dui-yu-flask-jin-qi-li-jie-de-yi-ge-gao-zi', Record<never, never>, Record<never, never>>,
    '/posts/history/ji-zhu-yue-du-shuang-cha-xun-yuan-li': RouteRecordInfo<'/posts/history/ji-zhu-yue-du-shuang-cha-xun-yuan-li', '/posts/history/ji-zhu-yue-du-shuang-cha-xun-yuan-li', Record<never, never>, Record<never, never>>,
    '/posts/history/ji-zhu-yue-du-web-huan-cun-tou-du': RouteRecordInfo<'/posts/history/ji-zhu-yue-du-web-huan-cun-tou-du', '/posts/history/ji-zhu-yue-du-web-huan-cun-tou-du', Record<never, never>, Record<never, never>>,
    '/posts/history/ji-zhu-yue-du-yong-github-lai-shi-xian-lou-dong-shang-jin-xi-ren': RouteRecordInfo<'/posts/history/ji-zhu-yue-du-yong-github-lai-shi-xian-lou-dong-shang-jin-xi-ren', '/posts/history/ji-zhu-yue-du-yong-github-lai-shi-xian-lou-dong-shang-jin-xi-ren', Record<never, never>, Record<never, never>>,
    '/posts/history/jwt-crack-zong-jie': RouteRecordInfo<'/posts/history/jwt-crack-zong-jie', '/posts/history/jwt-crack-zong-jie', Record<never, never>, Record<never, never>>,
    '/posts/history/length-extension-attack': RouteRecordInfo<'/posts/history/length-extension-attack', '/posts/history/length-extension-attack', Record<never, never>, Record<never, never>>,
    '/posts/history/lesslesszseanos-methodogygreatergreater-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/lesslesszseanos-methodogygreatergreater-xue-xi-bi-ji', '/posts/history/lesslesszseanos-methodogygreatergreater-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/li-jie-tls': RouteRecordInfo<'/posts/history/li-jie-tls', '/posts/history/li-jie-tls', Record<never, never>, Record<never, never>>,
    '/posts/history/linux-pian-pei-zhi-ni-de-aria2': RouteRecordInfo<'/posts/history/linux-pian-pei-zhi-ni-de-aria2', '/posts/history/linux-pian-pei-zhi-ni-de-aria2', Record<never, never>, Record<never, never>>,
    '/posts/history/linux-pian-pei-zhi-ni-de-aria2-wang-pan-xia-zai-dai-ti-xun-lei': RouteRecordInfo<'/posts/history/linux-pian-pei-zhi-ni-de-aria2-wang-pan-xia-zai-dai-ti-xun-lei', '/posts/history/linux-pian-pei-zhi-ni-de-aria2-wang-pan-xia-zai-dai-ti-xun-lei', Record<never, never>, Record<never, never>>,
    '/posts/history/php-fan-xu-lie-hua-bi-ji': RouteRecordInfo<'/posts/history/php-fan-xu-lie-hua-bi-ji', '/posts/history/php-fan-xu-lie-hua-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/san-openvpn-lian-jie-htb-bao-cuo-xiu-fu-verfiy-error': RouteRecordInfo<'/posts/history/san-openvpn-lian-jie-htb-bao-cuo-xiu-fu-verfiy-error', '/posts/history/san-openvpn-lian-jie-htb-bao-cuo-xiu-fu-verfiy-error', Record<never, never>, Record<never, never>>,
    '/posts/history/sddm-and-i3-mei-hua-and-za-tan': RouteRecordInfo<'/posts/history/sddm-and-i3-mei-hua-and-za-tan', '/posts/history/sddm-and-i3-mei-hua-and-za-tan', Record<never, never>, Record<never, never>>,
    '/posts/history/shen-ru-qian-chu-ssrf-wo-de-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/shen-ru-qian-chu-ssrf-wo-de-xue-xi-bi-ji', '/posts/history/shen-ru-qian-chu-ssrf-wo-de-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/shen-ru-qian-chu-ssrfer-wo-de-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/shen-ru-qian-chu-ssrfer-wo-de-xue-xi-bi-ji', '/posts/history/shen-ru-qian-chu-ssrfer-wo-de-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/shi-yong-celery-rang-ren-wu-zai-hou-tai-yun-xing-wei-wan': RouteRecordInfo<'/posts/history/shi-yong-celery-rang-ren-wu-zai-hou-tai-yun-xing-wei-wan', '/posts/history/shi-yong-celery-rang-ren-wu-zai-hou-tai-yun-xing-wei-wan', Record<never, never>, Record<never, never>>,
    '/posts/history/shua-ti-shui-ti-memcache-an-quan-xiang-guan': RouteRecordInfo<'/posts/history/shua-ti-shui-ti-memcache-an-quan-xiang-guan', '/posts/history/shua-ti-shui-ti-memcache-an-quan-xiang-guan', Record<never, never>, Record<never, never>>,
    '/posts/history/spring-ji-chu-gai-nian-bi-ji': RouteRecordInfo<'/posts/history/spring-ji-chu-gai-nian-bi-ji', '/posts/history/spring-ji-chu-gai-nian-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/synfony-rce-fen-xi': RouteRecordInfo<'/posts/history/synfony-rce-fen-xi', '/posts/history/synfony-rce-fen-xi', Record<never, never>, Record<never, never>>,
    '/posts/history/tui-jian-yi-xia-zi-ji-kai-fa-de-lun-tan-dan-han': RouteRecordInfo<'/posts/history/tui-jian-yi-xia-zi-ji-kai-fa-de-lun-tan-dan-han', '/posts/history/tui-jian-yi-xia-zi-ji-kai-fa-de-lun-tan-dan-han', Record<never, never>, Record<never, never>>,
    '/posts/history/vue-xue-xi-bi-ji': RouteRecordInfo<'/posts/history/vue-xue-xi-bi-ji', '/posts/history/vue-xue-xi-bi-ji', Record<never, never>, Record<never, never>>,
    '/posts/history/wafbypassshi-yong-python-fa-song-chunked': RouteRecordInfo<'/posts/history/wafbypassshi-yong-python-fa-song-chunked', '/posts/history/wafbypassshi-yong-python-fa-song-chunked', Record<never, never>, Record<never, never>>,
    '/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian': RouteRecordInfo<'/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian', '/posts/history/wo-de-gao-ji-ri-chang-po-zhen-kai-yuan-xi-tong-grapheneos-de-tui-jian', Record<never, never>, Record<never, never>>,
    '/posts/history/wo-de-xue-xi-bi-ji-he-yi-xie-xiang-mu': RouteRecordInfo<'/posts/history/wo-de-xue-xi-bi-ji-he-yi-xie-xiang-mu', '/posts/history/wo-de-xue-xi-bi-ji-he-yi-xie-xiang-mu', Record<never, never>, Record<never, never>>,
    '/posts/history/wo-hao-kun-11-yue-de-shui-wen-yi-fen': RouteRecordInfo<'/posts/history/wo-hao-kun-11-yue-de-shui-wen-yi-fen', '/posts/history/wo-hao-kun-11-yue-de-shui-wen-yi-fen', Record<never, never>, Record<never, never>>,
    '/posts/history/xian-cheng-bu-huo-keyboardinterrupter': RouteRecordInfo<'/posts/history/xian-cheng-bu-huo-keyboardinterrupter', '/posts/history/xian-cheng-bu-huo-keyboardinterrupter', Record<never, never>, Record<never, never>>,
    '/posts/history/xiao-wan-ju-kai-fa-tg-shou-qu-mailslurp-ni-ming-you-jian': RouteRecordInfo<'/posts/history/xiao-wan-ju-kai-fa-tg-shou-qu-mailslurp-ni-ming-you-jian', '/posts/history/xiao-wan-ju-kai-fa-tg-shou-qu-mailslurp-ni-ming-you-jian', Record<never, never>, Record<never, never>>,
    '/posts/history/xin-zhu-ti-cute-notes-and-jian-ming-er-ci-kai-fa-zhi-bei': RouteRecordInfo<'/posts/history/xin-zhu-ti-cute-notes-and-jian-ming-er-ci-kai-fa-zhi-bei', '/posts/history/xin-zhu-ti-cute-notes-and-jian-ming-er-ci-kai-fa-zhi-bei', Record<never, never>, Record<never, never>>,
    '/posts/history/xss-jin-jie-xue-xi-fen-xiang-yi': RouteRecordInfo<'/posts/history/xss-jin-jie-xue-xi-fen-xiang-yi', '/posts/history/xss-jin-jie-xue-xi-fen-xiang-yi', Record<never, never>, Record<never, never>>,
    '/posts/history/xss-shui-ti-pian-guan-yu-dom-colbbering-yi-xie-ge-ren-li-jie': RouteRecordInfo<'/posts/history/xss-shui-ti-pian-guan-yu-dom-colbbering-yi-xie-ge-ren-li-jie', '/posts/history/xss-shui-ti-pian-guan-yu-dom-colbbering-yi-xie-ge-ren-li-jie', Record<never, never>, Record<never, never>>,
    '/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian': RouteRecordInfo<'/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian', '/posts/history/yi-pian-zhen-dui-gong-zuo-hou-de-fan-si-huo-xu-de-sui-sui-nian', Record<never, never>, Record<never, never>>,
    '/posts/hola': RouteRecordInfo<'/posts/hola', '/posts/hola', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
